import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { english, french }

class LanguageService {
  LanguageService._();

  static final LanguageService instance = LanguageService._();

  static const _key = 'app_language';

  final ValueNotifier<AppLanguage> language =
      ValueNotifier(AppLanguage.english);

  AppLanguage get current => language.value;
  bool get isFrench => current == AppLanguage.french;
  String get code => isFrench ? 'fr' : 'en';
  String get localeName => isFrench ? 'fr_FR' : 'en_US';

  Future<void> loadFromStorage() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_key);
    language.value = code == 'fr' ? AppLanguage.french : AppLanguage.english;
    Intl.defaultLocale = localeName;
  }

  Future<void> setLanguage(AppLanguage value) async {
    language.value = value;
    Intl.defaultLocale = localeName;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, value == AppLanguage.french ? 'fr' : 'en');
  }

  String languageName(AppLanguage value) {
    if (isFrench) {
      return value == AppLanguage.french ? 'Francais' : 'Anglais';
    }
    return value == AppLanguage.french ? 'French' : 'English';
  }

  AppLanguage languageFromName(String value) {
    final normalized = value.trim().toLowerCase();
    if (normalized == 'french' || normalized == 'francais') {
      return AppLanguage.french;
    }
    return AppLanguage.english;
  }

  String t(String key, {Map<String, Object>? args}) {
    var value = (_strings[code]?[key] ?? _strings['en']?[key] ?? key);
    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value.toString());
      }
    }
    return value;
  }
}

const _strings = {
  'en': {
    'add_favorite': 'Add Favorite',
    // ── Admin: fleet ──────────────────────────────────────────────────────
    // ── Admin: dashboard ──────────────────────────────────────────────────
    // ── Admin: bookings ───────────────────────────────────────────────────
    'admin_bookings_title': 'Bookings',
    'admin_bookings_subtitle': 'Manage trips, update statuses, and edit booking records.',
    'admin_reject': 'Reject',
    'admin_details': 'Details',
    'admin_lbl_pickup': 'PICKUP',
    'admin_lbl_phone': 'PHONE',
    'admin_delete_booking': 'Delete booking?',
    'admin_delete_booking_confirm':
        'This permanently removes the booking record. This cannot be undone.',
    'admin_search_bookings': 'Search by name or destination',
    'admin_f_all': 'All',
    'admin_f_pending_approval': 'Pending Approval',
    'admin_backend_unavailable': 'Backend unavailable',
    'admin_no_bookings': 'No bookings yet',
    'admin_no_bookings_hint': 'Bookings created by clients will appear here.',
    'admin_no_match': 'Nothing matches',
    'admin_no_match_hint': 'Try a different status filter or search term.',
    // ── Admin: profile ────────────────────────────────────────────────────
    'admin_role_badge': 'ADMINISTRATOR',
    'admin_account': 'Account',
    'admin_permissions': 'Permissions',
    'admin_permissions_value': 'Full access — fleet, bookings, pricing, analytics',
    'admin_status': 'Status',
    'admin_status_active': 'Active',
    'admin_tools': 'Tools',
    'admin_link_ava': 'AVA Business Intelligence',
    'admin_link_ava_sub': 'Live insights and analytics by chat',
    'admin_link_promotions': 'Manage Promotions',
    'admin_link_promotions_sub': 'Promo codes and discounts',
    'admin_link_pricing': 'Pricing Configuration',
    'admin_link_pricing_sub': 'Per-vehicle rates and surcharges',
    'admin_logout_confirm': 'Sign out of the admin dashboard?',
    // ── Admin: AVA analytics ──────────────────────────────────────────────
    'admin_expand_chart': 'Expand chart',
    'admin_ava_p_review': 'Full business review',
    'admin_ava_p_revenue': 'Revenue by vehicle category',
    'admin_ava_p_pricing': 'How did pricing changes affect bookings?',
    'admin_ava_p_seasonal': 'Show seasonal booking trends',
    'admin_ava_p_pending': 'List all pending bookings',
    'admin_ava_p_complaints': 'Show me open complaints',
    'admin_dashboard_title': 'Admin Dashboard',
    'admin_dashboard_subtitle': 'Manage bookings, fleet, promotions, and pricing.',
    'admin_key_metrics': 'Key metrics',
    'admin_job_status': 'Job Status',
    'admin_revenue_split': 'Revenue Split',
    'admin_approve': 'Approve',
    'admin_from_completed': 'From {n} completed',
    'admin_n_pending': '{n} pending',
    'admin_registered': 'Registered accounts',
    'admin_manage_fleet_cap': 'Tap to manage',
    'admin_kpi_revenue': 'Total revenue',
    'admin_kpi_bookings': 'Total bookings',
    'admin_kpi_clients': 'Active clients',
    'admin_kpi_fleet': 'Fleet size',
    'admin_booking_trend': 'Bookings — last 7 days',
    'admin_revenue_by_category': 'Revenue by category',
    'admin_no_chart_data': 'No bookings in the last 7 days',
    'admin_no_revenue_yet': 'No completed revenue yet',
    'admin_status_breakdown': 'Status breakdown',
    'admin_st_pending': 'Pending',
    'admin_st_confirmed': 'Confirmed',
    'admin_st_on_route': 'On route',
    'admin_st_completed': 'Completed',
    'admin_st_cancelled': 'Cancelled',
    'admin_quick_actions': 'Quick actions',
    'admin_qa_bookings': 'Bookings',
    'admin_qa_fleet': 'Fleet',
    'admin_qa_promotions': 'Promotions',
    'admin_qa_pricing': 'Pricing',
    'admin_qa_complaints': 'Complaints',
    'admin_qa_suppliers': 'Suppliers',
    'admin_qa_destinations': 'Destinations',

    'reset_password_step2': 'Already have the reset code from your email? Enter it below with a new password.',
    'reset_password_token': 'Reset code',
    'reset_password_new': 'New password',
    'reset_password_apply': 'Set new password',
    'reset_password_needs_token': 'Enter the reset code and a password of at least 6 characters.',

    // AVA interactive booking cards
    'ava_bf_title': 'New booking',
    'ava_bf_from': 'FROM',
    'ava_bf_to': 'TO',
    'ava_bf_pickup': 'Pickup location',
    'ava_bf_destination': 'Destination',
    'ava_bf_place_hint': 'e.g. Tunis-Carthage Airport',
    'ava_bf_tap_enter': 'Tap to enter',
    'ava_bf_set': 'Set',
    'ava_bf_date': 'Date',
    'ava_bf_time': 'Time',
    'ava_bf_select': 'Select',
    'ava_bf_passengers': 'Passengers',
    'ava_bf_luggage': 'Luggage',
    'ava_bf_vehicle': 'Vehicle',
    'ava_bf_submit': 'Book this trip',
    'ava_bf_sent': 'Sent to AVA',
    'ava_bf_incomplete': 'Pick a date, time and vehicle to continue.',
    'ava_mb_title': 'Modify booking',
    'ava_mb_select': 'Select a booking',
    'ava_mb_what': 'What to change?',
    'ava_mb_new_date': 'New date',
    'ava_mb_new_time': 'New time',
    'ava_mb_save': 'Save changes',
    'ava_cb_title': 'Cancel booking',
    'ava_cb_select': 'Select a booking to cancel',
    'ava_cb_warning': 'This action cannot be undone.',
    'ava_cb_confirm': 'Cancel booking',
    'ava_cb_back': 'Go back',
    'ava_cb_dismissed': 'No booking was cancelled.',
    'ava_no_bookings': 'You have no upcoming bookings to change.',

    // Referral wallet at checkout
    'rewards_balance_row': 'Rewards balance',
    'rewards_balance_note':
        'Your referral balance is applied automatically to this booking.',
    'rewards_applied_success': '{amount} rewards balance applied',

    // AVA client screen
    'ava_lounge_hero': 'How may I assist you today?',
    'ava_lounge_hint': 'Ask about your trips, our fleet, or anything else.',
    'ava_input_hint': 'Message AVA...',
    'ava_voice_unavailable': 'Voice input is not available on this device.',
    'ava_sg_change_trip': 'Change my upcoming trip',
    'ava_sg_driver': "Where's my driver?",
    'ava_sg_meet_greet': 'Airport meet-and-greet',
    'ava_sg_rewards': 'My rewards & benefits',

    // Fleet capacity filtering
    'fleet_filter_notice':
        'Showing vehicles for {passengers} passengers, {luggage} bags',
    'fleet_filter_notice_hidden':
        'Showing vehicles for {passengers} passengers, {luggage} bags — {hidden} too small to fit',
    'fleet_no_fit_title': 'No vehicle fits your group',
    'fleet_no_fit_body':
        'None of our vehicles can carry {passengers} passengers with {luggage} bags. Try reducing the passengers or luggage.',
    'fleet_no_fit_action': 'Change my search',

    // Admin promotions + loyalty programme
    'admin_loyalty_programme': 'Loyalty programme',
    'admin_loyalty_members': '{n} members',
    'admin_loyalty_referred': 'Referred signups',
    'admin_loyalty_pending': 'Awaiting first ride',
    'admin_loyalty_member_codes': 'Member codes issued',
    'admin_scope_all': 'All codes',
    'admin_scope_campaign': 'Campaign',
    'admin_scope_member': 'Member rewards',
    'admin_no_promos': 'No promotions yet.',
    'admin_no_member_codes':
        'No member reward codes yet. They are issued automatically on signup, tier changes and referrals.',
    'admin_member_code': 'Member reward',
    'admin_origin_tier': 'Tier',
    'admin_origin_referral': 'Referral',
    'admin_origin_welcome': 'Welcome',
    'admin_origin_campaign': 'Campaign',

    // Admin booking status control
    'admin_change_status': 'Change status',
    'admin_adv_confirm': 'Confirm booking',
    'admin_adv_start': 'Start trip (on route)',
    'admin_adv_complete': 'Mark as completed',

    // AVA analytics — card sections
    'ava_key_findings': 'KEY FINDINGS',
    'ava_recommendation': 'Recommendation:',
    'ava_key_insights': 'KEY INSIGHTS',
    'ava_explore_next': 'EXPLORE NEXT',
    // AVA analytics — quick-action / follow-up chips
    'ava_chip_full_review': 'Full business review',
    'ava_chip_revenue': 'Revenue breakdown',
    'ava_chip_bookings': 'Booking trends',
    'ava_chip_pricing': 'Pricing impact',
    'ava_chip_seasonal': 'Seasonal patterns',
    'ava_chip_vehicles': 'Fleet performance',
    'ava_chip_complaints': 'Open complaints',
    'ava_chip_pending': 'Pending bookings',
    'ava_follow_by_vehicle': 'Break down by vehicle',
    'ava_follow_revenue_side': 'Revenue side',
    'admin_recent_activity': 'Recent bookings',
    'admin_pending_approvals': 'Pending Cash Approvals',
    'admin_pending_approvals_subtitle': 'Cash bookings waiting for your confirmation',
    'admin_booking_approval': 'Booking approval',
    'admin_client': 'Client',
    'admin_route': 'Route',
    'admin_vehicle': 'Vehicle',
    'admin_total': 'Total',
    'admin_approve_booking': 'Approve Booking',
    'admin_fleet_title': 'Fleet',
    'admin_fleet_subtitle': 'Manage vehicles and availability',
    'admin_add_car': 'Add car',
    'admin_edit_vehicle': 'Edit vehicle',
    'admin_add_vehicle': 'Add vehicle',
    'admin_vehicle_name': 'Name',
    'admin_vehicle_model': 'Model',
    'admin_category': 'Category',
    'admin_seats': 'Seats',
    'admin_luggage': 'Luggage',
    'admin_available': 'Available',
    'admin_unavailable': 'Unavailable',
    'admin_image_section': 'Image',
    'admin_image_url': 'Image URL (https or assets path)',
    'admin_pricing_eur': 'Pricing (EUR)',
    'admin_p_initial': 'Initial fee',
    'admin_p_initial_return': 'Initial fee (return)',
    'admin_p_per_km': 'Per km',
    'admin_p_per_km_return': 'Per km (return)',
    'admin_p_per_hour': 'Per hour',
    'admin_p_per_extra_hour': 'Per extra hour',
    'admin_p_per_waypoint': 'Per waypoint',
    'admin_p_per_waypoint_min': 'Per waypoint minute',
    'admin_features_section': 'Features',
    'admin_features_hint': 'Comma-separated, e.g. Private Transfer, AC',
    'admin_required': 'Required',
    'admin_invalid_value': 'Invalid value',
    'admin_delete_vehicle': 'Delete vehicle',
    'admin_delete_vehicle_confirm': 'Remove "{name}" from the fleet?',
    'admin_no_vehicles': 'No vehicles in the fleet yet.',
    'admin_retry': 'Retry',
    'admin_edit': 'Edit',
    'add_new_location': 'Add New Location',
    'address': 'Address',
    'alerts': 'Alerts',
    // ── Home: AVA card + travel tips ──────────────────────────────────────
    'your_destination': 'Your destination',
    'where_to': 'Where to?',
    'book_now': 'Book Now',
    'ava_home_title': 'Need help? Ask AVA',
    'ava_home_subtitle': 'Your AI concierge — tap to chat, hold to speak',
    'ava_listening': 'Listening...',
    'our_fleet': 'Our Fleet',
    'our_fleet_subtitle': 'Curated for executive comfort',
    'from_price': 'from',
    'no_vehicles': 'No vehicles available right now.',
    'travel_tips': 'Travel Tips',
    'travel_tips_subtitle': 'Good to know before you ride',
    'read_more': 'Read more',
    'ask_ava': 'Ask AVA about this',
    'tip_cat_faq': 'FAQ',
    'tip_cat_destinations': 'Destinations',
    'tip_cat_fleet': 'Fleet',
    'tip_cat_pricing': 'Pricing',
    // ── Notifications / misc ──────────────────────────────────────────────
    'notifications': 'Notifications',
    // ── Favorites: places autocomplete + memories ─────────────────────────
    'search_address': 'Search address',
    'location_name': 'Location name',
    'memories': 'Memories',
    'add_photo': 'Add Photo',
    'no_memories_yet': 'No photos yet',
    'photo_failed': 'Could not add that photo. Please try again.',
    'add_first_memory': 'Add your first memory of this place.',
    'choose_from_gallery': 'Choose from gallery',
    'take_photo': 'Take a photo',
    'delete_photo': 'Delete photo?',
    'delete_photo_confirm': 'This photo will be removed from this place.',
    'delete_location_photos_confirm':
        'Remove {name} and all of its photos? This cannot be undone.',
    // ── Rewards ───────────────────────────────────────────────────────────
    'your_promo_code': 'Your promo code',
    'copy_code': 'Copy code',
    'code_copied': 'Code copied to clipboard',
    'uses_remaining': '{used} of {total} uses remaining',
    'unlimited_uses': 'Unlimited uses',
    'expires_on': 'Expires {date}',
    'code_fully_used': 'Fully used — a new code arrives next cycle',
    'welcome_offer': 'Welcome offer',
    'referral_title': 'Invite a friend',
    'referral_desc':
        'Share your code — earn 5 EUR when your friend takes their first ride.',
    'your_referral_code': 'Your referral code',
    'referral_credits': 'Referral credits',
    'share': 'Share',
    'alerts_empty': 'No alerts yet. Booking updates will appear here.',
    'alerts_subtitle': 'Booking updates and offers',
    'airport': 'Airport',
    'airport_service_desc': 'Meet and greet transfers',
    'available_promo_codes': 'Available Promo Codes',
    'booking_cancel_note':
        'This will mark the reservation as cancelled. Your booking history will keep the record.',
    'booking_modify_limit':
        'Modification is only allowed {hours} hours before departure.',
    'booking_minimum':
        'Bookings must be made at least {hours} hours before departure.',
    'booking_cancel_limit':
        'Cancellation is only allowed {hours} hours before departure.',
    'booking_pickup_destination_required':
        'Add pickup and destination locations.',
    'booking_return_required': 'Choose return date and time.',
    'booking_time_required': 'Choose departure date and time.',
    'bookings': 'Bookings',
    'book_transfer': 'Book your transfer',
    'business': 'Business',
    'business_service_desc': 'Executive city rides',
    'call_support': 'Call support',
    'cancel': 'Cancel',
    'canceled': 'Canceled',
    'confirm_cancellation': 'Confirm Cancellation',
    'date': 'Date',
    'custom': 'Custom',
    'departure': 'Departure',
    'destination': 'Destination',
    'destination_hint': 'Hotel, city, or address',
    'display_preferences': 'Language and display preferences',
    'done': 'DONE',
    'drivers': 'Drivers',
    'earn': 'EARN',
    'edit_profile': 'Edit Profile',
    'favorites': 'Favorites',
    'favorite_label_hint': 'Home, Work, Airport',
    'favorites_subtitle': 'Home, work, airport, and custom locations',
    'fixed': 'Fixed',
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon',
    'good_evening': 'Good Evening',
    'experience_excellence': 'EXPERIENCE EXCELLENCE',
    'group': 'Group',
    'group_service_desc': 'Van and family transfers',
    'guest': 'Guest',
    'guest_browsing': 'Guest browsing',
    'guest_profile': 'Guest Profile',
    'history': 'History',
    'home': 'Home',
    'instant_response': 'Instant response',
    'just_now': 'Just now',
    'label': 'Label',
    'language': 'Language',
    'licensed': 'Licensed',
    'light_mode': 'Light mode',
    'light_mode_desc': 'Bright ivory interface with gold accents',
    'login': 'Login',
    'login_or_register': 'Login or Register',
    'login_required_favorites': 'Login to save personal locations',
    'login_to_reserve': 'Login to reserve rides',
    'logout': 'Logout',
    'luggage': 'Luggage',
    'mark_all_read': 'Mark all read',
    'modify': 'Modify',
    'modify_booking': 'Modify Booking',
    'modify_booking_subtitle': 'Allowed until {hours} hours before pickup',
    'booking_updated': 'Booking updated successfully',
    'my_bookings': 'My Bookings',
    'my_bookings_desc': 'Modify, cancel, or review reservations',
    'my_rides': 'My Rides',
    'my_rides_subtitle': 'Upcoming transfers and ride history',
    'no_canceled_rides': 'No canceled rides yet.',
    'no_history_rides': 'No history rides yet.',
    'no_upcoming_rides': 'No upcoming rides yet.',
    'passengers': 'Passengers',
    'pickup': 'Pickup',
    'pickup_hint': 'Pickup location',
    'pickup_location': 'Pickup location',
    'popular_destinations': 'Popular destinations',
    'popular_destinations_subtitle': 'Airport transfers and fixed routes',
    'preferences': 'Preferences',
    'premium_rides': 'Premium rides, trusted drivers',
    'profile': 'Profile',
    'profile_subtitle': 'Account, settings, and support',
    'promo_code': 'Promo code',
    'pricing': 'Pricing',
    'reservation_update': 'Reservation update',
    'return': 'Return',
    'return_time': 'Return time',
    'rewards': 'Rewards',
    'rewards_desc': 'Promo codes and ride milestones',
    'rewards_subtitle': 'Travel more, earn more',
    'rides': 'Rides',
    'routes': 'Routes',
    'round_trip': 'Round Trip',
    'safe': 'Safe',
    'save_changes': 'Save Changes',
    'save_location': 'Save Location',
    'saved_location': 'Saved location',
    'street_hint': 'Street, area, or landmark',
    'search_book': 'Search & Book',
    'secure': 'Secure',
    'select': 'Select',
    'services': 'Services',
    'services_subtitle': 'Premium transfer options for travelers',
    'settings': 'Settings',
    'support': 'Support',
    'support_available': 'Available 24/7',
    'support_desc': '24/7 transfer assistance',
    'time': 'Time',
    'to': 'to',
    'trip_status_changed': 'Your booking status changed.',
    'upcoming': 'Upcoming',
    'vehicle_categories': 'Vehicle categories',
    'vehicle_categories_subtitle': 'Browse the fleet before booking',
    'view_all': 'View all',
    'work': 'Work',
    'your_rewards': 'Your Rewards',
    'dark_mode': 'Dark mode',
    'dark_mode_desc': 'Premium black and gold interface',
    'already_have_account': 'Already have an account? ',
    'confirm_password': 'Confirm Password',
    'create_account': 'Create Account',
    'email_or_phone': 'Email or Phone Number',
    'every_time': 'Every time.',
    'forgot_password': 'Forgot Password?',
    'full_name': 'Full Name',
    'login_subtitle': 'Login to your account',
    'no_account': "Don't have an account? ",
    'password': 'Password',
    'reset_password': 'Reset Password',
    'reset_password_body':
        'Enter your account email and we will send you a reset link.',
    'reset_email_label': 'Email Address',
    'reset_email_invalid': 'Enter a valid email address.',
    'reset_password_sent':
        'Reset instructions have been queued for the admin team.',
    'send_reset_link': 'Send Reset Link',
    'signup': 'Sign Up',
    'signup_subtitle': 'Sign up to get started',
    'terms_accept': 'I agree to the Terms & Conditions',
    'terms_required': 'Please accept the terms to continue.',
    'welcome_back': 'Welcome Back',
    'one_way': 'One Way',
    // Notifications
    'alerts_hero_subtitle':
        'Stay updated on your executive journeys and rewards.',
    'today': 'TODAY',
    'yesterday': 'YESTERDAY',
    'earlier': 'EARLIER',
    'all_clear': 'All Clear',
    'alerts_empty_subtitle':
        'No alerts at the moment.\nYour executive journeys are running smoothly.',
    'selected_count': '{count} Selected',
    'select_all': 'Select All',
    'deselect_all': 'Deselect All',
    'mark_read': 'Mark read',
    'delete_selected': 'Delete selected',
    'notification_deleted': 'Notification deleted',
    'undo': 'Undo',
    'delete': 'DELETE',
    'notification': 'Notification',
    'no_details': 'No details available.',
    'time_now': 'now',
    'time_just_now': 'Just now',
    'time_minutes_ago': '{n}m ago',
    'time_hours_ago': '{n}h ago',
    'time_yesterday': 'Yesterday',
    'time_days_ago': '{n}d ago',
    // Trips (My Rides)
    'rides_hero_subtitle':
        'Track upcoming transfers and review your ride history.',
    'no_rides_empty_action': 'Book a transfer',
    'ride_modify': 'Modify',
    'ride_cancel': 'Cancel',
    'ride_details': 'Details',
    'status_upcoming': 'Upcoming',
    'status_completed': 'Completed',
    'status_cancelled': 'Cancelled',
    'status_in_progress': 'In progress',
    // Saved (Favorites)
    'saved_hero_subtitle':
        'Quick-pick your home, work, airport, and frequent stops.',
    'no_saved_locations': 'No saved locations yet.',
    'add_first_location': 'Add your first location',
    'edit': 'Edit',
    'delete_location': 'Delete location',
    'delete_location_confirm':
        'Remove this saved location? You can always add it again.',
    'remove': 'Remove',
  },
  'fr': {
    'add_favorite': 'Ajouter un favori',
    // ── Admin : flotte ────────────────────────────────────────────────────
    // ── Admin : tableau de bord ───────────────────────────────────────────
    // ── Admin : reservations ──────────────────────────────────────────────
    'admin_bookings_title': 'Reservations',
    'admin_bookings_subtitle': 'Gerez les trajets, statuts et fiches de reservation.',
    'admin_reject': 'Rejeter',
    'admin_details': 'Details',
    'admin_lbl_pickup': 'DEPART',
    'admin_lbl_phone': 'TELEPHONE',
    'admin_delete_booking': 'Supprimer la reservation ?',
    'admin_delete_booking_confirm':
        'La fiche sera definitivement supprimee. Action irreversible.',
    'admin_search_bookings': 'Rechercher par nom ou destination',
    'admin_f_all': 'Toutes',
    'admin_f_pending_approval': 'A approuver',
    'admin_backend_unavailable': 'Serveur indisponible',
    'admin_no_bookings': 'Aucune reservation',
    'admin_no_bookings_hint': 'Les reservations des clients apparaitront ici.',
    'admin_no_match': 'Aucun resultat',
    'admin_no_match_hint': 'Essayez un autre filtre ou terme de recherche.',
    // ── Admin : profil ────────────────────────────────────────────────────
    'admin_role_badge': 'ADMINISTRATEUR',
    'admin_account': 'Compte',
    'admin_permissions': 'Permissions',
    'admin_permissions_value': 'Acces complet — flotte, reservations, tarifs, analyses',
    'admin_status': 'Statut',
    'admin_status_active': 'Actif',
    'admin_tools': 'Outils',
    'admin_link_ava': 'AVA Business Intelligence',
    'admin_link_ava_sub': 'Analyses et insights en direct par chat',
    'admin_link_promotions': 'Gerer les promotions',
    'admin_link_promotions_sub': 'Codes promo et remises',
    'admin_link_pricing': 'Configuration tarifaire',
    'admin_link_pricing_sub': 'Tarifs par vehicule et majorations',
    'admin_logout_confirm': 'Se deconnecter du tableau de bord ?',
    // ── Admin : analyses AVA ──────────────────────────────────────────────
    'admin_expand_chart': 'Agrandir',
    'admin_ava_p_review': 'Bilan complet de l activite',
    'admin_ava_p_revenue': 'Revenu par categorie de vehicule',
    'admin_ava_p_pricing': 'Impact des changements de tarifs ?',
    'admin_ava_p_seasonal': 'Tendances saisonnieres des reservations',
    'admin_ava_p_pending': 'Lister les reservations en attente',
    'admin_ava_p_complaints': 'Afficher les reclamations ouvertes',
    'admin_dashboard_title': 'Tableau de bord',
    'admin_dashboard_subtitle': 'Gerez reservations, flotte, promotions et tarifs.',
    'admin_key_metrics': 'Indicateurs cles',
    'admin_job_status': 'Statut des courses',
    'admin_revenue_split': 'Repartition du revenu',
    'admin_approve': 'Approuver',
    'admin_from_completed': 'Sur {n} terminees',
    'admin_n_pending': '{n} en attente',
    'admin_registered': 'Comptes enregistres',
    'admin_manage_fleet_cap': 'Toucher pour gerer',
    'admin_kpi_revenue': 'Revenu total',
    'admin_kpi_bookings': 'Reservations',
    'admin_kpi_clients': 'Clients actifs',
    'admin_kpi_fleet': 'Vehicules',
    'admin_booking_trend': 'Reservations — 7 derniers jours',
    'admin_revenue_by_category': 'Revenu par categorie',
    'admin_no_chart_data': 'Aucune reservation ces 7 derniers jours',
    'admin_no_revenue_yet': 'Aucun revenu finalise pour le moment',
    'admin_status_breakdown': 'Repartition des statuts',
    'admin_st_pending': 'En attente',
    'admin_st_confirmed': 'Confirmee',
    'admin_st_on_route': 'En route',
    'admin_st_completed': 'Terminee',
    'admin_st_cancelled': 'Annulee',
    'admin_quick_actions': 'Actions rapides',
    'admin_qa_bookings': 'Reservations',
    'admin_qa_fleet': 'Flotte',
    'admin_qa_promotions': 'Promotions',
    'admin_qa_pricing': 'Tarifs',
    'admin_qa_complaints': 'Reclamations',
    'admin_qa_suppliers': 'Fournisseurs',
    'admin_qa_destinations': 'Destinations',

    'reset_password_step2': 'Vous avez deja le code recu par email ? Saisissez-le avec un nouveau mot de passe.',
    'reset_password_token': 'Code de reinitialisation',
    'reset_password_new': 'Nouveau mot de passe',
    'reset_password_apply': 'Definir le mot de passe',
    'reset_password_needs_token': 'Saisissez le code et un mot de passe d au moins 6 caracteres.',

    // Cartes de reservation interactives AVA
    'ava_bf_title': 'Nouvelle reservation',
    'ava_bf_from': 'DE',
    'ava_bf_to': 'A',
    'ava_bf_pickup': 'Lieu de prise en charge',
    'ava_bf_destination': 'Destination',
    'ava_bf_place_hint': 'ex. Aeroport Tunis-Carthage',
    'ava_bf_tap_enter': 'Appuyez pour saisir',
    'ava_bf_set': 'Valider',
    'ava_bf_date': 'Date',
    'ava_bf_time': 'Heure',
    'ava_bf_select': 'Choisir',
    'ava_bf_passengers': 'Passagers',
    'ava_bf_luggage': 'Bagages',
    'ava_bf_vehicle': 'Vehicule',
    'ava_bf_submit': 'Reserver ce trajet',
    'ava_bf_sent': 'Envoye a AVA',
    'ava_bf_incomplete': 'Choisissez une date, une heure et un vehicule.',
    'ava_mb_title': 'Modifier la reservation',
    'ava_mb_select': 'Selectionnez une reservation',
    'ava_mb_what': 'Que modifier ?',
    'ava_mb_new_date': 'Nouvelle date',
    'ava_mb_new_time': 'Nouvelle heure',
    'ava_mb_save': 'Enregistrer',
    'ava_cb_title': 'Annuler la reservation',
    'ava_cb_select': 'Selectionnez la reservation a annuler',
    'ava_cb_warning': 'Cette action est irreversible.',
    'ava_cb_confirm': 'Annuler',
    'ava_cb_back': 'Retour',
    'ava_cb_dismissed': 'Aucune reservation annulee.',
    'ava_no_bookings': 'Vous n avez aucune reservation a modifier.',

    // Portefeuille de parrainage au paiement
    'rewards_balance_row': 'Solde de recompenses',
    'rewards_balance_note':
        'Votre solde de parrainage est applique automatiquement a cette reservation.',
    'rewards_applied_success': '{amount} de recompenses appliques',

    // Ecran AVA (client)
    'ava_lounge_hero': 'Comment puis-je vous aider ?',
    'ava_lounge_hint':
        'Posez vos questions sur vos trajets, notre flotte, ou autre.',
    'ava_input_hint': 'Message a AVA...',
    'ava_voice_unavailable':
        'La saisie vocale n est pas disponible sur cet appareil.',
    'ava_sg_change_trip': 'Modifier mon trajet',
    'ava_sg_driver': 'Ou est mon chauffeur ?',
    'ava_sg_meet_greet': 'Accueil a l aeroport',
    'ava_sg_rewards': 'Mes recompenses',

    // Filtrage de la flotte par capacite
    'fleet_filter_notice':
        'Vehicules pour {passengers} passagers, {luggage} bagages',
    'fleet_filter_notice_hidden':
        'Vehicules pour {passengers} passagers, {luggage} bagages — {hidden} trop petits',
    'fleet_no_fit_title': 'Aucun vehicule adapte a votre groupe',
    'fleet_no_fit_body':
        'Aucun de nos vehicules ne peut transporter {passengers} passagers avec {luggage} bagages. Reduisez les passagers ou les bagages.',
    'fleet_no_fit_action': 'Modifier ma recherche',

    // Promotions et programme de fidelite (admin)
    'admin_loyalty_programme': 'Programme de fidelite',
    'admin_loyalty_members': '{n} membres',
    'admin_loyalty_referred': 'Inscriptions parrainees',
    'admin_loyalty_pending': 'En attente du 1er trajet',
    'admin_loyalty_member_codes': 'Codes membres emis',
    'admin_scope_all': 'Tous les codes',
    'admin_scope_campaign': 'Campagne',
    'admin_scope_member': 'Recompenses membres',
    'admin_no_promos': 'Aucune promotion pour le moment.',
    'admin_no_member_codes':
        'Aucun code de recompense. Ils sont emis automatiquement a l inscription, au changement de palier et au parrainage.',
    'admin_member_code': 'Recompense membre',
    'admin_origin_tier': 'Palier',
    'admin_origin_referral': 'Parrainage',
    'admin_origin_welcome': 'Bienvenue',
    'admin_origin_campaign': 'Campagne',

    // Controle du statut des reservations (admin)
    'admin_change_status': 'Changer le statut',
    'admin_adv_confirm': 'Confirmer la reservation',
    'admin_adv_start': 'Demarrer le trajet (en route)',
    'admin_adv_complete': 'Marquer comme terminee',

    // AVA analytics — sections de la carte
    'ava_key_findings': 'CONSTATS CLES',
    'ava_recommendation': 'Recommandation :',
    'ava_key_insights': 'POINTS CLES',
    'ava_explore_next': 'EXPLORER ENSUITE',
    // AVA analytics — puces d'action rapide / de suivi
    'ava_chip_full_review': 'Bilan complet',
    'ava_chip_revenue': 'Analyse des revenus',
    'ava_chip_bookings': 'Tendances des reservations',
    'ava_chip_pricing': 'Impact tarifaire',
    'ava_chip_seasonal': 'Tendances saisonnieres',
    'ava_chip_vehicles': 'Performance de la flotte',
    'ava_chip_complaints': 'Reclamations ouvertes',
    'ava_chip_pending': 'Reservations en attente',
    'ava_follow_by_vehicle': 'Detail par vehicule',
    'ava_follow_revenue_side': 'Cote revenus',
    'admin_recent_activity': 'Reservations recentes',
    'admin_pending_approvals': 'Approbations en attente',
    'admin_pending_approvals_subtitle': 'Reservations en especes en attente de confirmation',
    'admin_booking_approval': 'Approbation de reservation',
    'admin_client': 'Client',
    'admin_route': 'Trajet',
    'admin_vehicle': 'Vehicule',
    'admin_total': 'Total',
    'admin_approve_booking': 'Approuver la reservation',
    'admin_fleet_title': 'Flotte',
    'admin_fleet_subtitle': 'Gerez les vehicules et la disponibilite',
    'admin_add_car': 'Ajouter',
    'admin_edit_vehicle': 'Modifier le vehicule',
    'admin_add_vehicle': 'Ajouter un vehicule',
    'admin_vehicle_name': 'Nom',
    'admin_vehicle_model': 'Modele',
    'admin_category': 'Categorie',
    'admin_seats': 'Places',
    'admin_luggage': 'Bagages',
    'admin_available': 'Disponible',
    'admin_unavailable': 'Indisponible',
    'admin_image_section': 'Image',
    'admin_image_url': 'URL de l image (https ou chemin assets)',
    'admin_pricing_eur': 'Tarification (EUR)',
    'admin_p_initial': 'Frais initial',
    'admin_p_initial_return': 'Frais initial (retour)',
    'admin_p_per_km': 'Par km',
    'admin_p_per_km_return': 'Par km (retour)',
    'admin_p_per_hour': 'Par heure',
    'admin_p_per_extra_hour': 'Par heure supp.',
    'admin_p_per_waypoint': 'Par etape',
    'admin_p_per_waypoint_min': 'Par minute d etape',
    'admin_features_section': 'Prestations',
    'admin_features_hint': 'Separees par des virgules, ex. Transfert prive, Clim',
    'admin_required': 'Requis',
    'admin_invalid_value': 'Valeur invalide',
    'admin_delete_vehicle': 'Supprimer le vehicule',
    'admin_delete_vehicle_confirm': 'Retirer "{name}" de la flotte ?',
    'admin_no_vehicles': 'Aucun vehicule dans la flotte.',
    'admin_retry': 'Reessayer',
    'admin_edit': 'Modifier',
    'add_new_location': 'Ajouter une adresse',
    'address': 'Adresse',
    'alerts': 'Alertes',
    // ── Accueil : carte AVA + conseils ────────────────────────────────────
    'your_destination': 'Votre destination',
    'where_to': 'Ou allez-vous ?',
    'book_now': 'Reserver',
    'ava_home_title': 'Besoin d aide ? Demandez a AVA',
    'ava_home_subtitle':
        'Votre concierge IA — touchez pour ecrire, maintenez pour parler',
    'ava_listening': 'Ecoute en cours...',
    'our_fleet': 'Notre flotte',
    'our_fleet_subtitle': 'Selectionnee pour le confort executif',
    'from_price': 'a partir de',
    'no_vehicles': 'Aucun vehicule disponible actuellement.',
    'travel_tips': 'Conseils de voyage',
    'travel_tips_subtitle': 'Bon a savoir avant de partir',
    'read_more': 'Lire la suite',
    'ask_ava': 'Demander a AVA',
    'tip_cat_faq': 'FAQ',
    'tip_cat_destinations': 'Destinations',
    'tip_cat_fleet': 'Flotte',
    'tip_cat_pricing': 'Tarifs',
    // ── Notifications / divers ────────────────────────────────────────────
    'notifications': 'Notifications',
    // ── Favoris : adresse + souvenirs ─────────────────────────────────────
    'search_address': 'Rechercher une adresse',
    'location_name': 'Nom du lieu',
    'memories': 'Souvenirs',
    'add_photo': 'Ajouter une photo',
    'no_memories_yet': 'Aucune photo pour le moment',
    'photo_failed': 'Impossible d ajouter cette photo. Veuillez reessayer.',
    'add_first_memory': 'Ajoutez votre premier souvenir de ce lieu.',
    'choose_from_gallery': 'Choisir dans la galerie',
    'take_photo': 'Prendre une photo',
    'delete_photo': 'Supprimer la photo ?',
    'delete_photo_confirm': 'Cette photo sera retiree de ce lieu.',
    'delete_location_photos_confirm':
        'Supprimer {name} et toutes ses photos ? Action irreversible.',
    // ── Fidelite ──────────────────────────────────────────────────────────
    'your_promo_code': 'Votre code promo',
    'copy_code': 'Copier le code',
    'code_copied': 'Code copie dans le presse-papiers',
    'uses_remaining': '{used} sur {total} utilisations restantes',
    'unlimited_uses': 'Utilisations illimitees',
    'expires_on': 'Expire le {date}',
    'code_fully_used': 'Entierement utilise — un nouveau code au prochain cycle',
    'welcome_offer': 'Offre de bienvenue',
    'referral_title': 'Parrainez un ami',
    'referral_desc':
        'Partagez votre code — gagnez 5 EUR des le premier trajet de votre ami.',
    'your_referral_code': 'Votre code de parrainage',
    'referral_credits': 'Credits de parrainage',
    'share': 'Partager',
    'alerts_empty':
        'Aucune alerte pour le moment. Les mises a jour apparaitront ici.',
    'alerts_subtitle': 'Mises a jour de reservation et offres',
    'airport': 'Aeroport',
    'airport_service_desc': 'Accueil et transferts aeroport',
    'available_promo_codes': 'Codes promo disponibles',
    'booking_cancel_note':
        'Cette action marquera la reservation comme annulee. Votre historique conservera cette course.',
    'booking_modify_limit':
        'La modification est possible jusqu a {hours} heures avant le depart.',
    'booking_minimum':
        'Les reservations doivent etre faites au moins {hours} heures avant le depart.',
    'booking_cancel_limit':
        'L annulation est possible jusqu a {hours} heures avant le depart.',
    'booking_pickup_destination_required':
        'Ajoutez le lieu de prise en charge et la destination.',
    'booking_return_required': 'Choisissez la date et l heure de retour.',
    'booking_time_required': 'Choisissez la date et l heure de depart.',
    'bookings': 'Reservations',
    'book_transfer': 'Reserver votre transfert',
    'business': 'Business',
    'business_service_desc': 'Trajets executifs en ville',
    'call_support': 'Appeler le support',
    'cancel': 'Annuler',
    'canceled': 'Annulees',
    'confirm_cancellation': 'Confirmer l annulation',
    'date': 'Date',
    'custom': 'Perso',
    'departure': 'Depart',
    'destination': 'Destination',
    'destination_hint': 'Hotel, ville ou adresse',
    'display_preferences': 'Langue et mode d affichage',
    'done': 'TERMINE',
    'drivers': 'pro',
    'earn': 'GAGNER',
    'edit_profile': 'Modifier le profil',
    'favorites': 'Favoris',
    'favorite_label_hint': 'Maison, Travail, Aeroport',
    'favorites_subtitle': 'Maison, travail, aeroport et adresses perso',
    'fixed': 'Prix',
    'good_morning': 'Bonjour',
    'good_afternoon': 'Bon apres-midi',
    'good_evening': 'Bonsoir',
    'experience_excellence': 'L EXCELLENCE AU QUOTIDIEN',
    'group': 'Groupe',
    'group_service_desc': 'Vans et transferts famille',
    'guest': 'Invite',
    'guest_browsing': 'Navigation invite',
    'guest_profile': 'Profil invite',
    'history': 'Historique',
    'home': 'Accueil',
    'instant_response': 'Reponse instantanee',
    'just_now': 'A l instant',
    'label': 'Libelle',
    'language': 'Langue',
    'licensed': 'Chauffeurs',
    'light_mode': 'Mode clair',
    'light_mode_desc': 'Interface ivoire lumineuse avec accents or',
    'login': 'Connexion',
    'login_or_register': 'Connexion ou inscription',
    'login_required_favorites': 'Connectez-vous pour enregistrer vos adresses',
    'login_to_reserve': 'Connectez-vous pour reserver',
    'logout': 'Deconnexion',
    'luggage': 'Bagages',
    'mark_all_read': 'Tout marquer comme lu',
    'modify': 'Modifier',
    'modify_booking': 'Modifier la reservation',
    'modify_booking_subtitle':
        'Autorise jusqu a {hours} heures avant la prise en charge',
    'booking_updated': 'Reservation mise a jour avec succes',
    'my_bookings': 'Mes reservations',
    'my_bookings_desc': 'Modifier, annuler ou consulter vos reservations',
    'my_rides': 'Mes courses',
    'my_rides_subtitle': 'Transferts a venir et historique',
    'no_canceled_rides': 'Aucune course annulee.',
    'no_history_rides': 'Aucun historique de course.',
    'no_upcoming_rides': 'Aucune course a venir.',
    'passengers': 'Passagers',
    'pickup': 'Prise en charge',
    'pickup_hint': 'Lieu de prise en charge',
    'pickup_location': 'Lieu de prise en charge',
    'popular_destinations': 'Destinations populaires',
    'popular_destinations_subtitle': 'Transferts aeroport et routes fixes',
    'preferences': 'Preferences',
    'premium_rides': 'Trajets premium, chauffeurs de confiance',
    'profile': 'Profil',
    'profile_subtitle': 'Compte, parametres et support',
    'promo_code': 'Code promo',
    'pricing': 'fixes',
    'reservation_update': 'Mise a jour de reservation',
    'return': 'Retour',
    'return_time': 'Heure retour',
    'rewards': 'Recompenses',
    'rewards_desc': 'Codes promo et objectifs de trajet',
    'rewards_subtitle': 'Voyagez plus, gagnez plus',
    'rides': 'courses',
    'routes': 'Routes',
    'round_trip': 'Aller-retour',
    'safe': 'Securise',
    'save_changes': 'Enregistrer',
    'save_location': 'Enregistrer l adresse',
    'saved_location': 'Adresse enregistree',
    'street_hint': 'Rue, zone ou point de repere',
    'search_book': 'Rechercher et reserver',
    'secure': 'premium',
    'select': 'Choisir',
    'services': 'Services',
    'services_subtitle': 'Options de transfert premium',
    'settings': 'Parametres',
    'support': 'Support',
    'support_available': 'Disponible 24/7',
    'support_desc': 'Assistance transfert 24/7',
    'time': 'Heure',
    'to': 'vers',
    'trip_status_changed': 'Le statut de votre reservation a change.',
    'upcoming': 'A venir',
    'vehicle_categories': 'Categories de vehicules',
    'vehicle_categories_subtitle': 'Parcourez la flotte avant de reserver',
    'view_all': 'Voir tout',
    'work': 'Travail',
    'your_rewards': 'Vos recompenses',
    'dark_mode': 'Mode sombre',
    'dark_mode_desc': 'Interface noire premium avec accents or',
    'already_have_account': 'Vous avez deja un compte ? ',
    'confirm_password': 'Confirmer le mot de passe',
    'create_account': 'Creer un compte',
    'email_or_phone': 'Email ou numero de telephone',
    'every_time': 'A chaque trajet.',
    'forgot_password': 'Mot de passe oublie ?',
    'full_name': 'Nom complet',
    'login_subtitle': 'Connectez-vous a votre compte',
    'no_account': 'Vous n avez pas de compte ? ',
    'password': 'Mot de passe',
    'reset_password': 'Reinitialiser le mot de passe',
    'reset_password_body':
        'Entrez l email de votre compte et nous vous enverrons un lien.',
    'reset_email_label': 'Adresse e-mail',
    'reset_email_invalid': 'Saisissez une adresse e-mail valide.',
    'reset_password_sent':
        'Les instructions de reinitialisation ont ete transmises a l equipe admin.',
    'send_reset_link': 'Envoyer le lien',
    'signup': 'Inscription',
    'signup_subtitle': 'Inscrivez-vous pour commencer',
    'terms_accept': 'J accepte les conditions generales',
    'terms_required': 'Veuillez accepter les conditions pour continuer.',
    'welcome_back': 'Bon retour',
    'one_way': 'Aller simple',
    // Notifications
    'alerts_hero_subtitle':
        'Suivez vos courses executives et vos recompenses.',
    'today': 'AUJOURD HUI',
    'yesterday': 'HIER',
    'earlier': 'PLUS TOT',
    'all_clear': 'Tout est calme',
    'alerts_empty_subtitle':
        'Aucune alerte pour le moment.\nVos courses executives se deroulent normalement.',
    'selected_count': '{count} selectionnee(s)',
    'select_all': 'Tout selectionner',
    'deselect_all': 'Tout deselectionner',
    'mark_read': 'Marquer lu',
    'delete_selected': 'Supprimer la selection',
    'notification_deleted': 'Notification supprimee',
    'undo': 'Annuler',
    'delete': 'SUPPRIMER',
    'notification': 'Notification',
    'no_details': 'Aucun detail disponible.',
    'time_now': 'maintenant',
    'time_just_now': 'A l instant',
    'time_minutes_ago': 'il y a {n} min',
    'time_hours_ago': 'il y a {n} h',
    'time_yesterday': 'Hier',
    'time_days_ago': 'il y a {n} j',
    // Trips (My Rides)
    'rides_hero_subtitle':
        'Suivez vos transferts a venir et consultez votre historique.',
    'no_rides_empty_action': 'Reserver un transfert',
    'ride_modify': 'Modifier',
    'ride_cancel': 'Annuler',
    'ride_details': 'Details',
    'status_upcoming': 'A venir',
    'status_completed': 'Terminee',
    'status_cancelled': 'Annulee',
    'status_in_progress': 'En cours',
    // Saved (Favorites)
    'saved_hero_subtitle':
        'Acces rapide a votre domicile, bureau, aeroport et arrets frequents.',
    'no_saved_locations': 'Aucune adresse enregistree.',
    'add_first_location': 'Ajouter votre premiere adresse',
    'edit': 'Modifier',
    'delete_location': 'Supprimer l adresse',
    'delete_location_confirm':
        'Supprimer cette adresse enregistree ? Vous pourrez toujours l ajouter a nouveau.',
    'remove': 'Supprimer',
  },
};
